services:
  tennis-api:
    build: .
    container_name: tennis-predictor-api
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
    volumes:
      - ./atp_tennis.csv:/app/atp_tennis.csv
    restart: unless-stopped
